name: ChampionChecker.UI
services:
  xampp:
    container_name: xampp
    image: championchecker.ui/xampp
    build:
      context: . 
      dockerfile: dockerfile
      args:
        GITHUB_PAT: ${GITHUB_PAT} # GitHub Personal Access Token, wird aus lokaler .env-Datei gelesen
    ports:
      - "80:80"
      - "443:443"
