name: ChampionChecker.UI
services:
  xampp:
    container_name: xampp
    image: tomsik68/xampp:8
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - /c/xampp/htdocs/ChampionChecker.UI:/opt/lampp/htdocs/ChampionChecker.UI
