<!DOCTYPE html>
<html lang="de">

<head>
	<link rel="stylesheet/less" type="text/css" href="styles/styles.less" />
	<script src="https://cdn.jsdelivr.net/npm/less"></script>
	<meta charset="utf-8">
	<meta name="description" content="Endergebnis Tischtennis">

	<title>Klassenpunkte Eintragen</title>
</head>

<body>
	<header>
		<h1>Klassenpunkte</h1>
	</header>

	<main class="main-content">

		<?php

		require_once __DIR__ . '/MVC/Model/ClassModel.php';
		require_once __DIR__ . '/MVC/Model/Competition.php';

		require_once __DIR__ . '/MVC/Controller/IController.php';
		require_once __DIR__ . '/MVC/Controller/ClassController.php';
		require_once __DIR__ . '/MVC/Controller/CompetitionController.php';

		use MVC\Controller\ClassController;
		use MVC\Controller\CompetitionController;

		$classController = new ClassController();
		$classes = $classController->getAll();
		$participantClassesNames = [];

		foreach ($classes as $class) {
			$participantClassesNames[] = $class->getName();
		}

		$competitionController = new CompetitionController();
		$competitionModels = $competitionController->getAll();
		$teamCompetitions = array("Mannschaft" => []);
		$soloCompetitions = array("Einzeln" => []);

		foreach ($competitionModels as $comp) {
			if ($comp->getIsTeam()) {
				$teamCompetitions["Mannschaft"][] = $comp->getName();
			} else {
				$soloCompetitions["Einzeln"][] = $comp->getName();
			}
		}
		?>

		<div class="styled-select">
			<select name="classes">
				<option value="">Klasse auswählen:</option>
				<?php foreach (
					$participantClassesNames
					as $participantClassName
				): ?>
					<option value="<?= $participantClassName ?>">
						<?= $participantClassName ?>
					</option>
				<?php endforeach; ?>
			</select>
		</div>

		<div class="styled-select">
			<select name="competitions">
				<option value="">Wettbewerb auswählen:</option>
				<?php foreach ($teamCompetitions as $key => $compNames): ?>
					<optgroup label="<?= $key ?>">
						<?php foreach ($compNames as $name): ?>
							<option value="<?= $name ?>">
								<?= $name ?>
							</option>
						<?php endforeach; ?>
					<?php endforeach; ?>
				<?php foreach ($soloCompetitions as $key => $compNames): ?>
					<optgroup label="<?= $key ?>">
						<?php foreach ($compNames as $name): ?>
							<option value="<?= $name ?>">
								<?= $name ?>
							</option>
						<?php endforeach; ?>
					<?php endforeach; ?>
			</select>
		</div>

		<input name="points" placeholder="Punktzahl eingeben:" type="number" Punktzahl eingeben:"
			type="text" required minlength="1" maxlength="2" />

		<button type="submit" name="submit" value="Abschicken">Abschicken</button>
	</main>
	<footer />
	</footer>
</body>

</html>